# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con_list', '0002_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emal',
            new_name='email',
        ),
    ]
