# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con_list', '0003_auto_20170902_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
